# Generated by Django 5.0.1 on 2024-01-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_follower_follower_alter_follower_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='following',
        ),
    ]
