# Generated by Django 5.0.1 on 2024-01-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_follower_follower_remove_follower_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
